version: "3.0"
services:
  redis:
    image: redis:latest
    environment:
      ACCEPT_EULA:"1"
      MSSQL_SA_PASSWORD:"Password@1"
    ports:
      -"6379:6379"
    volumes:
      - ./data:/data
volumes:
  redis-data: